### ISSUE TITLE
Do env variables work when running against Cloud? 

### ISSUE THREAD

**Issue by KamalAman** [grafana/k6-action#12]
Envs don't seem to take effect when running against the cloud.

**Comment by DefCon-007** [comment]
To use environment variables when running the test in cloud, you set the variables in your organization settings and then reference them in your scripts. For more information on this, tale a look [here](https://k6.io/docs/cloud/manage/environment-variables/#manage-environment-variables).

Also, when starting tests with `k6 cloud`, environment variables set via CLI flag `--env` and environment variables set in the cloud are combined and used together to run the test. If an environment variable is both set via CLI and declared in the cloud, the value set via the CLI will be applied instead of the value set in the cloud.
